### ISSUE TITLE
Tamed example doesn't work

### ISSUE THREAD

**Issue by kylelt** [kumpelblase2/Remote-Entities#39]
I tried many ways to get an npc following a player, and then I even tried the example to make sure it was broken and it really does seem to be broken. It is likely that I am doing something wrong... But the example it self isn't working for me but here is the error:
 [SEVERE] net.minecraft.server.v1_4_R1.ReportedException: Ticking entity
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:583)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:228)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:489)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:421)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
2013-03-16 10:14:33 [SEVERE] Caused by: java.lang.NullPointerException
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.EntityPlayer.g(EntityPlayer.java:212)
2013-03-16 10:14:33 [SEVERE]    at de.kumpelblase2.remoteentities.entities.RemotePlayerEntity.j_(RemotePlayerEntity.java:110)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.World.entityJoinedWorld(World.java:1427)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.WorldServer.entityJoinedWorld(WorldServer.java:587)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.World.playerJoinedWorld(World.java:1407)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.World.tickEntities(World.java:1269)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.WorldServer.tickEntities(WorldServer.java:478)
2013-03-16 10:14:33 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:579)
2013-03-16 10:14:33 [SEVERE]    ... 4 more
2013-03-16 10:14:33 [SEVERE] Encountered an unexpected exception ReportedException
net.minecraft.server.v1_4_R1.ReportedException: Ticking entity
    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:583)
    at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:228)
    at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:489)
    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:421)
    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at net.minecraft.server.v1_4_R1.EntityPlayer.g(EntityPlayer.java:212)
    at de.kumpelblase2.remoteentities.entities.RemotePlayerEntity.j_(RemotePlayerEntity.java:110)
    at net.minecraft.server.v1_4_R1.World.entityJoinedWorld(World.java:1427)
    at net.minecraft.server.v1_4_R1.WorldServer.entityJoinedWorld(WorldServer.java:587)
    at net.minecraft.server.v1_4_R1.World.playerJoinedWorld(World.java:1407)
    at net.minecraft.server.v1_4_R1.World.tickEntities(World.java:1269)
    at net.minecraft.server.v1_4_R1.WorldServer.tickEntities(WorldServer.java:478)
    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:579)
    ... 4 more

**Comment by kylelt** [comment]
I have also tried several other things using the player object and it seems to break every time...

**Comment by confuser** [comment]
Try DesireFollowSpecific instead of tame

**Comment by kumpelblase2** [comment]
This is not caused by remote entities rather than by bukkit. The stacktrace does only refer to lines which are nms code and are not related to remote entities at all.
