### ISSUE TITLE
Ticking entity exception

### ISSUE THREAD

**Issue by ghost** [kumpelblase2/Remote-Entities#42]
Using CB 1.5.1 beta 0.2

remoteentities-1.6-20130409.201627-9.jar

```
2013-04-15 19:19:04 [SEVERE] net.minecraft.server.v1_5_R2.ReportedException: Ticking entity
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:566)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
2013-04-15 19:19:04 [SEVERE] Caused by: java.util.ConcurrentModificationException
2013-04-15 19:19:04 [SEVERE]    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
2013-04-15 19:19:04 [SEVERE]    at java.util.ArrayList$Itr.next(Unknown Source)
2013-04-15 19:19:04 [SEVERE]    at de.kumpelblase2.remoteentities.api.thinking.DesireSelector.onUpdate(DesireSelector.java:30)
2013-04-15 19:19:04 [SEVERE]    at de.kumpelblase2.remoteentities.api.thinking.Mind.tick(Mind.java:388)
2013-04-15 19:19:04 [SEVERE]    at de.kumpelblase2.remoteentities.entities.RemoteZombieEntity.l_(RemoteZombieEntity.java:85)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.World.entityJoinedWorld(World.java:1355)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.WorldServer.entityJoinedWorld(WorldServer.java:614)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.World.playerJoinedWorld(World.java:1336)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.World.tickEntities(World.java:1224)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.WorldServer.tickEntities(WorldServer.java:480)
2013-04-15 19:19:04 [SEVERE]    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:562)
2013-04-15 19:19:04 [SEVERE]    ... 4 more
2013-04-15 19:19:04 [SEVERE] Encountered an unexpected exception ReportedException
net.minecraft.server.v1_5_R2.ReportedException: Ticking entity
        at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:566)
        at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at de.kumpelblase2.remoteentities.api.thinking.DesireSelector.onUpdate(DesireSelector.java:30)
        at de.kumpelblase2.remoteentities.api.thinking.Mind.tick(Mind.java:388)
        at de.kumpelblase2.remoteentities.entities.RemoteZombieEntity.l_(RemoteZombieEntity.java:85)
        at net.minecraft.server.v1_5_R2.World.entityJoinedWorld(World.java:1355)
        at net.minecraft.server.v1_5_R2.WorldServer.entityJoinedWorld(WorldServer.java:614)
        at net.minecraft.server.v1_5_R2.World.playerJoinedWorld(World.java:1336)
        at net.minecraft.server.v1_5_R2.World.tickEntities(World.java:1224)
        at net.minecraft.server.v1_5_R2.WorldServer.tickEntities(WorldServer.java:480)
        at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:562)
        ... 4 more
```

Produced by the following code:

```
public void test(Location loc, int c) {
        for (int i = 0; i < c; i++) {
            double slice = ((Math.PI*2)/c)*i;
            Location nloc = loc.clone();
            nloc.add(Math.sin(slice)*20.0,0.0,Math.cos(slice)*20.0);
            RemoteEntity e = this.npcManager.createEntity(RemoteEntityType.Zombie, nloc, true);
            e.getMind().addMovementDesire(new DesireMoveToLocation(e, loc), 1);
        }
    }
```

The zombies spawn in a circle and move towards the location. When they arrive within a few blocks, the server crashes with the error above.

**Comment by kumpelblase2** [comment]
Fixed in https://github.com/kumpelblase2/Remote-Entities/commit/1f4557e767d631a683a90ba6c813cafceea97f0b .
