### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Lolmewn** [kumpelblase2/Remote-Entities#7]
I've found a small issue while loading the server.
This is the error:

20:57:54 [INFO] [Quests] [Debug] Handling 2 with id 2
20:57:54 [WARNING] [Quests] Task #208 for Quests vjenkins-Quests-47 generated an exce
ption
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
        at java.util.HashMap$EntryIterator.next(Unknown Source)
        at java.util.HashMap$EntryIterator.next(Unknown Source)
        at de.kumpelblase2.remoteentities.EntityManager$1.run(EntityManager.java:39)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftS
cheduler.java:345)
        at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:529)
        at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
20:57:54 [INFO] [Quests] [Debug] Added NPC 2 at Location{world=CraftWorld{name=main},
x=100.59259102955416,y=64.0,z=0.055737997258818894,pitch=0.0,yaw=-227.0}

This happened while starting the server. NPC's were being loaded (as you can see by the debug code), when this happened. I think something must be made thread-safe perhaps?

**Comment by kumpelblase2** [comment]
Yeah, might be a good idea, never actually though about that. Sorry.

**Comment by kumpelblase2** [comment]
Seeing this as fixed by latest version.
