### ISSUE TITLE
NPE on ChunkUnloadEvent

### ISSUE THREAD

**Issue by mastergberry** [kumpelblase2/Remote-Entities#77]
`[19:51:23 WARN]: [RemoteEntities] Task #6323 for RemoteEntities v1.8-SNAPSHOT generated an exception
java.lang.NullPointerException
        at de.kumpelblase2.remoteentities.ChunkEntityLoader$2.run(ChunkEntityLoader.java:70) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[spigot.jar:git-Spigot-1.7.2-R0.2-89-g0875998]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot.jar:git-Spigot-1.7.2-R0.2-89-g0875998]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:583) [spigot.jar:git-Spigot-1.7.2-R0.2-89-g0875998]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1.7.2-R0.2-89-g0875998]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:540) [spigot.jar:git-Spigot-1.7.2-R0.2-89-g0875998]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:446) [spigot.jar:git-Spigot-1.7.2-R0.2-89-g0875998]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.2-89-g0875998]`

Appears that rentity is null on line 69.

**Comment by kolinkrewinkel** [comment]
The easy thing to do would be simply to add an if (!= null) there, but the _right_ thing to do would be to find why they effectively don't agree. I'll take a look.

**Comment by kolinkrewinkel** [comment]
Actually, because there's a check here (https://github.com/kumpelblase2/Remote-Entities/blob/master/src/main/java/de/kumpelblase2/remoteentities/EntityManager.java#L303), it's possible to get rid of the isRemoteEntity on line 67, and simply use getRemoteEntity() and check for null. From a semantics point of view, it's also better.

**Comment by kumpelblase2** [comment]
I will take a look at it tomorrow after I finished redoing the updating process.

**Comment by kolinkrewinkel** [comment]
Took care of it. (I think. My change is at least a sound one, but I'm not sure that it addresses the underlying issue, which should be a separate one—not NPE, which my PR fixes, but a logical one.)
